### ISSUE TITLE
[BUG] Weigher API is not available in Store 4

### ISSUE THREAD

**Issue by tasomaniac** [dropbox/Store#153]
**Describe the bug**
The Store 4 does not have the `Weigher` APIs as before in Cache APIs. This was an important part of the API since size of the cache is not always enough. Especially when the cache has values that are in variety of the size (byte), it is important to have a limit on the memory space. It allows us to keep small items and remove bigger ones when the cache is full. 

**To Reproduce**
Upgrade an already existing code with Store 3 to Store 4. 

**Expected behavior**
The `maximumWieght` function and `Weigher` interface should be available.

**Comment by digitalbuddha** [comment]
I took a stab at it, I bit more complicated than I would have hoped. Store4 Builder does not take a parameterized types. That is a necessity to support weigher.  I see 3 options:
1. We add <K,V> to all builders
1. We subclass Store.Builder with WeighingStoreBuilder
1. We make weigher a non type safe api

2 was the advantage of being able to enforce cross param validation specific to weighers in a build function rather than in each setter like the following:

```override fun maxWeight( weight:Long){
        require(maxSize == UNSET_LONG) {"maximum size was already set to $maxSize"};
        maximumWeight = weight;
    }
```

Let me know what works for everyone and I can get it in.  I'll get everything but the builder done first

**Comment by tasomaniac** [comment]
2 is definitely a decent option. What is the disadvantage of 1? Is it just unnecessary overhead to the builder APIs?

**Comment by digitalbuddha** [comment]
Yup unnecessary bloat to others. Thanks for chiming in will go with 2.
