### ISSUE TITLE
[BUG] Allow nullable types in FetcherResult

### ISSUE THREAD

**Issue by hansenji** [dropbox/Store#164]
**Describe the bug**
FetcherResult doesn't allow for nullable types. This is extremely useful when you are by passing the fetcher due to data validation/cache checks

**Expected behavior**
Allow nullable types in FetcherResult

**Comment by yigit** [comment]
if data validation fails, isn't that an error?

And for cache, are you referring to http cache headers ?
I think we could consider adding a FetcherResponse type for `Unchanged` but if `sourceOfTruth` does not have the value for some reason, it might created unexpected problems.

**Comment by hansenji** [comment]
No this is a case where we can't use the http cache headers and we have a separate caching mechanism due to uncontrolled services. We check our `sourceOfTruth` in the fetcher code so we know we have the data.

**Comment by eyalgu** [comment]
@hansenji - would your use-case be solved by closing the flow without returning a value?

I don't know how well we actually support empty fetcher `Flow` (though it's part of the API so we should support well enough).

We would need to figure out exactly what to do in the case the `Flow` didn't return anything.
In the case of `stream` we will probably try to fall back to `cache` of `sourceOfTruth`, but we will need to figure out what to do if both are empty...
not sure what's the expected behavior for `fresh` etc.

@yigit thoughts?

**Comment by hansenji** [comment]
I am using a `nonFlowFetcher` so I can't just close the flow. `Unchanged` would work perfectly. 

I misspoke when I mentioned data validation that should definitely be an error. But I really need a solution for self caching due to uncontrolled service restrictions.

**Comment by eyalgu** [comment]
`nonFlowFetcher` is a connivance for a "regular" fetcher. Will this work for you?
`StoreBuilder.from(fetcher = { key -> flowOf { mySuspendFetcher(key}?.let { emit(it) } })`

**Comment by hansenji** [comment]
This works great. I wish I could use the convenience functions but this works well.
