### ISSUE TITLE
[QUESTION] How to handle Exception from writer

### ISSUE THREAD

**Issue by almeric** [dropbox/Store#177]
Hi,
First of all, thanks for this amazing library!

I'm probably doing something wrong, but I can't seem to catch an exception thrown from the writer when using `fresh`

Take this example:

```kotlin
val store = StoreBuilder.from<Any, Int, Int>(
    fetcher = nonFlowValueFetcher {
        1
    },
    sourceOfTruth = SourceOfTruth.from(
        reader = {
            flowOf(1)
        },
        writer = { _, _ ->
            throw SQLiteException()
        }
    )
).build()
viewModelScope.launch(handler) {
    try {
        val result = store.fresh(1)
        Timber.d("RESULT, $result")
    } catch (t: Throwable) {
        Timber.e(t, "CAUGHT")
    }
}

```
I can wrap writing to the database in a try/catch inside the writer, but that way it will fail silently & I'd like to be able to catch it in the ViewModel so I can inform the user of the error.

Any ideas?

**Comment by yigit** [comment]
hmm i guess somewhere we are swallowing the exception :/.

thanks for the repro.

**Comment by almeric** [comment]
Thanks for the reply!

The app does crash when throwing in the writer, so the exception eventually reaches the UncaughtExceptionHandler. I'm just unable to catch it at the call site.

**Comment by eyalgu** [comment]
The issue is that we have no handling for the write call to the SoT, which happens in the actor (and crashes it).

We can solve it by catching the exception there, but need to decide on how to handle it. We also have to deal with our value throttling logic that currently does not apply to errors.
We have a few, not great options:

1) terminate the flow if the SoT errors out. This might be the safest/simplest option but not great for usability.
2) transform the value to an error and propagate it to downstreams. If we do this we will also need to add error to our throttling mechanism, otherwise an error from SoT can cause us to peg the fetcher. This may be the nicest yet most complex solution
3) Silently Ignore SoT errors. This can mean  that if a developer who sets up the SoT incorrectly will never know they are not updating it
4) Add a side channel to report write errors. Dirties up the API and will probably not be used by most people

I’m leaning toward 2
