### ISSUE TITLE
[BUG] "NoSuchElementException: Expected at least one element" when mocking Store

### ISSUE THREAD

**Issue by harmittaa** [dropbox/Store#223]
**Describe the bug**
Upon mocking Store behaviour with Mockito or MockK an exception will be thrown.

MockK:  https://gist.github.com/harmittaa/4687a476734def3c6c6f385a785c2157#file-exampletest-kt-L72
Mockito: https://gist.github.com/harmittaa/a7a06c2ef55788228ee031dcac2a19b0#file-exampletest-kt-L72

**To Reproduce**
1. Clone the repo
2. Add MockK dependency to app's gradle `testImplementation "io.mockk:mockk:1.9.2"` (or use mockito)
3. In `Graph.kt` remove `private` visibility modifier of `toPosts` and `provideRetrofit`
4. Add the following file with test and mock classes somewhere in the app module: https://gist.github.com/harmittaa/4687a476734def3c6c6f385a785c2157 or https://gist.github.com/harmittaa/a7a06c2ef55788228ee031dcac2a19b0
5. Run test

**Expected behavior**
Mocking `Store` behaviour should not cause an exception

**Comment by digitalbuddha** [comment]
I've never used store with mocking frameworks and am not sure what the issue is here. Your issue only revalidates me hating them. Generally it is recommended to make fakes rather than mocks. All layers of a store are backed by interfaces which make it a breeze to swap in a fake. Take a look at how we test stores https://github.com/dropbox/Store/blob/main/store/src/test/java/com/dropbox/android/external/store4/impl/FlowStoreTest.kt#L59

I'll leave the issue open but do not think anyone will take a look at this pre 1.0 release. We do not have the context for what mockk is doing. If you can reproduce without a 3rd party lib, I'd take a look

**Comment by marekdef** [comment]
I looked at the mockk example and what made me think was this stacktrace element

```
at com.dropbox.android.external.store4.StoreKt.fresh(Store.kt:84)
```

that should not be called because it was mocked in the test
```
coEvery { store.fresh(any()) } returns mockk()
```

but then I realise this is a static function, so in order to be a ble to mock this you need
```
mockkStatic("com.dropbox.android.external.store4.StoreKt")
```
then this test does not fail.

For mockito I guess you would need to mock stream method that is called by fresh

**Comment by eyalgu** [comment]
`store.fresh` is an extension function and not part of the store class so you cannot mock it directly:
```
suspend fun <Key : Any, Output : Any> Store<Key, Output>.fresh(key: Key) = stream(
    StoreRequest.fresh(key)
).filterNot {
    it is StoreResponse.Loading || it is StoreResponse.NoNewData
}.first().requireData()
```
mock `stream` instead.

That being said, you'd probably be better off avoiding mocking store and using a simple fake impl or test `Fetcher` in a real store.
