### ISSUE TITLE
[Question] Cancelation of requests

### ISSUE THREAD

**Issue by aartikov** [dropbox/Store#225]
When does store cancel fetcher requests? Does it do it when there are no active streams for a given key?
Is it possible to cancel requests manually? 

My use case: 
I have a store that loads a user profile. I want to cancel loading and remove a profile as part of logout operation. Otherwise it is hard to guaranty an absence of profile in database after logout is completed.

**Comment by aartikov** [comment]
@eyalgu Could you please help with the question?

**Comment by eyalgu** [comment]
Yes, the fetcher request will be canceled when there are no more active streams for a given key.

We currently do not provide a way to manually cancel a request

Quick impl note - due to limitation with the current multicasting logic, we don't have a way to wait for the fetcher's cancellation before completing the cancelation of the (last) stream. That means that even though we do cancel the upstream there can be a small delay between the cancellation of the last stream and the cancelation of the upstream.

If you absolutely want to guarantee for not that no new data is written to the SoT after logout, you can add a check in the SourceOfTruth's writer function for now.

Providing a stronger cancellation guarantee is something we should probably add in a future version

**Comment by eyalgu** [comment]
Note - we can probably get rid of a lot of custom code and this limitation once [SharedFlow](https://github.com/Kotlin/kotlinx.coroutines/issues/2034) is out (in the next coroutine release hopefully)
