### ISSUE TITLE
[BUG] Nothing happens when a cachePolicy is set

### ISSUE THREAD

**Issue by sanders9** [dropbox/Store#258]
**Describe the bug**

As described in the repo I configured a CachePolicy to clear the cache after a period of time (10s). Unfortunately nothing happens

**To Reproduce**

Only configure a CachePolicy. Please find below my implementation : 

```
  @OptIn(ExperimentalTime::class)
  @ExperimentalCoroutinesApi
  @FlowPreview
  private val storeQuery = StoreBuilder.from(
      fetcher = Fetcher.of { publication: Publication -> delegate.queryPublications(currentType, publication) },
      sourceOfTruth = SourceOfTruth.of(
          reader = { _: Publication ->
            db.publicationDao().getAllPublications(currentType).map {
              if(it.isEmpty())
              {
                null
              }
              else{
                val result = PublicationResult.Success(it)
                result
              }
            }
          },
          writer = { _: Publication, input: Flow<PublicationResult> ->
            db.publicationDao().insertPublication(currentType, input.first())
          },
          delete = { key: Publication ->
            db.publicationDao().deletePublication(NEIGHBOR, key)
          }
      )
  )
      .cachePolicy(
          MemoryPolicy.builder<Publication, PublicationResult>()
//              .setExpireAfterAccess(30.days)
              . setExpireAfterAccess(10.seconds)
              .build()
      )
      .build()
```

**Expected behavior**

I expected : 
1. either a call to `db.publicationDao().deletePublication(NEIGHBOR, key)` after 10s 
2. or automatically a clear of some db rows

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 11
 - Store Version: 4.0.0

**Comment by digitalbuddha** [comment]
Hi Sanders, the cache policy is for the in memory cache rather than the source of truth. Since store does not own your disk impl it cannot know about expiration policies. If you need to expire things on disk, I recommend keeping a timestamp within your publication table and checking if timestamp is past expiration when returning from your reader. If expired return null.

We are thinking of adding disk expiration policies but it is complicated since you need to persist the record policies for store and currently store doesn't have its own persistence. Hope that helps!

**Comment by sanders9** [comment]
Hi @digitalbuddha very clear and thanks for your support. I already have a timestamp in my table. I will implement a routine to clear the past data.
Have a nice day
