### ISSUE TITLE
Setting in-memory cache expiry is useless when source of truth is provided

### ISSUE THREAD

**Issue by ychescale9** [dropbox/Store#95]
After reading #73 and the [`RealStore`](https://github.com/dropbox/Store/blob/fd2219fcdee3d9583691f57bb1b8acf8606bad6f/store/src/main/java/com/dropbox/android/external/store4/impl/RealStore.kt#L108) implementation, I realized it's effectively useless to set `expireAfterAccess` or `expireAfterWrite` on the `MemoryPolicy` when a `sourceOfTruth` is provided to the store, as the disk value will be immediately backfilled to the cache after cache expiration. From the user's perspective, they'll get the data from the disk instead of cache (slightly slower) when cache has expired but the fetcher won't be triggered (unless they bypass Store and manually delete the entry from disk).

This behavior is inconsistent to when `sourceOfTruth == null`, in which case cache expiry will trigger the fetcher (thanks to `piggybackOnly`).

Should we try to make these 2 branches (with or without `sourceOfTruth`) behave consistently in terms of the effect of cache expiry?

I remember the old Store had a `networkBeforeStale()` API for triggering the fetcher if the disk entry is stale. Does it make sense to support this (on both memory cache and sourceOfTruth?)?

I understand that cache expiry and disk entry becoming stale could be interpreted as different concepts so unifying the behavior with or without `sourceOfTruth` might cause other confusions...

**Comment by digitalbuddha** [comment]
I noticed weirdness here too while working on the rxbindings. It feels unintuitive that a new fetcher request would be made if one is not already in progress.  @yigit thoughts on how you expect this to work?

**Comment by yigit** [comment]
> Should we try to make these 2 branches (with or without `sourceOfTruth`) behave consistently in terms of the effect of cache expiry?

No. I think there is a mis-understanding that `sourceOfTruth` is another layer of `persistent cache`. It is not, it is the source of truth as the local knows it. So trying to evaluate the behavior of source of truth based on cache will cause more confusion.

This is also why we call it source of truth explicitly, not just disk cache etc because it is not just a cache. Keep in mind that this architecture actually allowed TiVi to easily migrate as it can still do everything else it does w/ db and partially migrate as Store respects the existing source of truth.

The cache policy only effects the memory cache, nothing else. 
If someone wants to use a disk as a cache, we probably need to expand our cache APIs to be pluggable for a persistent cache.
It is also the case that you almost never have both source of truth and disk cache, so maybe the API can work around it.

Unfortunately, Store cannot track (or trust) when certain requests are made since it'll require ability to persist keys. Also, if data is persisted on a database, we would need APIs to update timestamps in a transaction. Even worse, we cannot respect the source of truth as updates might happen outside Store.

On the other hand, I did like @chrisbanes's solution where he went w/ a callback function that would validate whether the local value (disk or network) is good enough to show.

So if we can figure out a lower level filtering API where some generic thing can filter local values and decide whether they are good enough or not, it might be the ultimate solution.

Also, most of this can be done w/ current APIs for disk but cannot be done for cache because we create it.
Might make sense to change it so that cache is also a given rather than something we build internally.

**Comment by ychescale9** [comment]
> The cache policy only effects the memory cache, nothing else.
If someone wants to use a disk as a cache, we probably need to expand our cache APIs to be pluggable for a persistent cache.
It is also the case that you almost never have both source of truth and disk cache, so maybe the API can work around it.

As the most common case is probably just in-memory cache + persister (source of truth), should we document to make it clear that setting expiry policy has no effect in this case (I.e does not trigger fetcher) and removing the current 24hour expiry default when source of truth is found?

**Comment by ychescale9** [comment]
> Might make sense to change it so that cache is also a given rather than something we build internally.

I’d like to see this happen and not having the Store create a cache by default so we can be less opinionated on what the default policy should be and we don’t need to do the additional mapping from the MemoryPolicyBuilder -> CacheBuilder.

I can give this a try if people are happy with this change.

**Comment by yigit** [comment]
I'll leave it to @digitalbuddha whether we need a cache by default or not. I'm fine both ways but I think he likes having a cache by default.
Also, it avoids the need to have a view model just to handle rotation so may not be bad.

As for the cache API, i think we've kind of ignored re-evaluating it as part of this rewrite.
In Store 3, afaik, persistence was just a persistent cache.
In Store 4, it is something else and the position of cache is more complicated.

I also don't want to close the door on having persistent cache. Sometimes, it is all what people want but has more complication (e.g. persistable keys).

I even think maybe we should re-evaluate what cahe means for Store and maybe make it an API where you pass in ( `suspend put`, `suspend get`) and let people implement it however they want ?

**Comment by ychescale9** [comment]
> I even think maybe we should re-evaluate what cahe means for Store and maybe make it an API where you pass in ( suspend put, suspend get) and let people implement it however they want ?

I like this and being able to not depend on the cache artifact. But I’m still interested in your (and **everyone else**) take on how the expiration policy should behave. In the ideal scenario should we have separate policies for cache and persister or is it possible to have a single policy after reevaluating the role of a cache for Store4?

@digitalbuddha @eyalgu please let me know if any of the documentation or cache policy API changes mentioned here makes sense:).

**Comment by yigit** [comment]
Well the downside of separating cache is that UX drops as they need another artifact just to do some reasonable caching. On the other hand though, i bet most people would use jsut and LRU cache and be OK with it.

It might actually make sense to also write the file persister and we can make that file persister and guava cache receive the same config type.

so for people who want to use store as a glorified cache can do so ?

**Comment by digitalbuddha** [comment]
My take is that backfilling the memory cache from disk is work as intended. The memory cache is an optimization in case persister reads are slow and causing screen flicker on rotation. I consinder source of truth as slow but cheap to read from, I don't think there is any concern of reading from local storage too much as far as I can tell.  I'm going to paste a code snippet on the other issue on how to handle not loading from network when disk value is good. I think that is the real issue.

Just my highly opinionated opinion and open to ways we can make this flexible without opening ourselves up to brittle apis

**Comment by ychescale9** [comment]
Assuming this is the intended behavior of memory cache, are there any tangible benefits of setting the expiry policy when the store has a source of truth?

I still feel that as a user I'd be surprised to find out that the effect of an in-memory cache expiring is drastically different depending on whether source-of-truth is present. It's almost like if source-of-truth is not present, the in-memory cache would implicitly become the source-of-truth (partially?).

Sorry I don't really have anything to propose yet but thought this might be something we want to think about more while in alpha.

**Comment by eyalgu** [comment]
> Assuming this is the intended behavior of memory cache, are there any tangible benefits of setting the expiry policy when the store has a source of truth?

Yes, You can get data from the memory cache rather than from disk

> I still feel that as a user I'd be surprised to find out that the effect of an in-memory cache expiring is drastically different depending on whether source-of-truth is present. It's almost like if source-of-truth is not present, the in-memory cache would implicitly become the source-of-truth (partially?).

Do you mean the experience of when you get device stored values vs remote values?

**Comment by ychescale9** [comment]
> Yes, You can get data from the memory cache rather than from disk

But you'll always get data from memory cache regardless of whether you set an expiry policy or not? The only difference I can see is that if you have an expiring memory cache you'll get `Persister` instead of `Cache` as the `ResponseOrigin` occasionally, which is not something I'd consider tangible e.g. user will hardly notice the if the app shows a different state for `StoreResponse.Loading`.

> Do you mean the experience of when you get device stored values vs remote values?

Yeah it's more that what triggers a remote data fetch feels unexpected. I guess this essentially comes down to the the limitation where in-memory cache supports expiry policy but `Persister` doesn't.

**Comment by eyalgu** [comment]
> user will hardly notice the if the app shows a different state for StoreResponse.Loading.
We can't really know that's true in all cases. I haven't measured disk read time on android in a while, but old devices can talk longer. someone trying to read from sqllite in an inefficient way can take a noticeable time as well. I don't think we can safely assume that under all circumstances are disk reads going to be fast enough that memory cache is un-necessary.

This does make me thing of an interesting optimization we might want to add in the future - the ability to check for a cached value synchronously rather than via suspend function. This could be useful if you're trying to perform an operation inline from the ui thread and want to try and get a cache value for a fast path (though I don't think we have seen the need for it so far).

> Yeah it's more that what triggers a remote data fetch feels unexpected.
Cache expiry is alway unexpected from the cache consumer's viewpoint. You never know if you're going to get a hit or miss. The cache is merely a perf optimization over reading from disk when disk is available (and has a bigger role when it's not). If the user wants a specify a fresh value fetch there's an API for that via the `StoreRequest`

**Comment by ychescale9** [comment]
Fair points. I wonder if we should document this difference in the role of cache depending on whether persister is provided?

**Comment by digitalbuddha** [comment]
#73 was closed. I don't think any changes are needed at this time. Please reopen with examples/issues that are specific to a use case
